version: '3.7'
services:
  ms-eureka:
    container_name: ms-eureka
    build: ./ms-eureka
    ports:
      - 8761:8761
    working_dir: /app
    networks:
      - ms_comprove_el_person

  db_storage:
    container_name: db_storage
    image: postgres
    environment:
      - POSTGRES_DB=db_storage
      - POSTGRES_USER=STORAGE
      - POSTGRES_PASSWORD=STORAGE
      - PGDATA=/data/postgres
    volumes:
      - ./V_db_storage:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db_comprove_el_person
    restart: unless-stopped

networks:
  db_comprove_el_person:
    driver: bridge
  ms_comprove_el_person:
    driver: bridge