version: '3.7'
services:
  ms-eureka:
    container_name: ms-eureka
    build: ./ms-eureka
    ports:
      - 8761:8761
    working_dir: /app
    networks:
      - ms_comprove_el_person

  db_storage:
    container_name: db_storage
    image: postgres
    environment:
      - POSTGRES_DB=db_storage
      - POSTGRES_USER=STORAGE
      - POSTGRES_PASSWORD=STORAGE
      - PGDATA=/data/postgres
    volumes:
      - ./V_db_storage:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db_comprove_el_person
    restart: unless-stopped

  ms-storage:
    container_name: ms-storage
    build: ./ms-storage
    ports:
      - 8081:8081
    environment:
      - EUREKA_URL=http://ms-eureka:8761/eureka
      - DB_STORAGE_URL=jdbc:postgresql://db_storage:5432/db_storage
      - DB_STORAGE_USERNAME=STORAGE
      - DB_STORAGE_PASSWORD=STORAGE
      - BASE_PATH_COMPROVE_PERSON_STORAGE=/app/volume/
    working_dir: /app
    volumes:
      - ./V_ms_storage:/app/volume/
    networks:
      - ms_comprove_el_person
      - db_comprove_el_person
    depends_on:
      - db_storage

  db_person:
    container_name: db_person
    image: postgres
    environment:
      - POSTGRES_DB=db_person
      - POSTGRES_USER=PERSON
      - POSTGRES_PASSWORD=PERSON
      - PGDATA=/data/postgres
    volumes:
      - ./V_db_person:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db_comprove_el_person
    restart: unless-stopped

networks:
  db_comprove_el_person:
    driver: bridge
  ms_comprove_el_person:
    driver: bridge